
#ifndef PANEL_FUNC_H
#define PANEL_FUNC_H

#include <libguile.h>
#include <config.h>
#ifdef DLL_EXPORT
#define API __attribute__ ((dllexport, cdecl))
#else
#define API
#endif
#define cstring_t cchar_t
// This file was autogenerated by func_head.awk
SCM gucu_bottom_panel (SCM arg1) API;
SCM gucu_top_panel (SCM arg1) API;
SCM gucu_show_panel (SCM arg1) API;
SCM gucu_update_panels (void) API;
SCM gucu_hide_panel (SCM arg1) API;
SCM gucu_panel_window (SCM arg1) API;
SCM gucu_replace_panel (SCM arg1, SCM arg2) API;
SCM gucu_move_panel (SCM arg1, SCM arg2, SCM arg3) API;
SCM gucu_panel_hidden_p (SCM arg1) API;

void gucu_panel_init_function (void) API;
#endif

